### ISSUE TITLE
missing env.POSTGRES?

### ISSUE THREAD

**Issue by avrljk** [UWA-FoS/docker-mytardis#1]
Following the README.md instructions...

$ git clone --recursive https://github.com/UWA-FoS/docker-mytardis.git mytardis
Cloning into 'mytardis'...
remote: Counting objects: 199, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 199 (delta 2), reused 6 (delta 2), pack-reused 193
Receiving objects: 100% (199/199), 59.69 KiB | 0 bytes/s, done.
Resolving deltas: 100% (109/109), done.
Submodule 'src/mydata' (https://github.com/wettenhj/mytardis-app-mydata) registered for path 'src/mydata'
Submodule 'src/mytardis' (https://github.com/mytardis/mytardis.git) registered for path 'src/mytardis'
Cloning into 'src/mydata'...
remote: Counting objects: 287, done.
remote: Total 287 (delta 0), reused 0 (delta 0), pack-reused 287
Receiving objects: 100% (287/287), 56.00 KiB | 0 bytes/s, done.
Resolving deltas: 100% (156/156), done.
Submodule path 'src/mydata': checked out 'eac68ec7c09ac1e674d5aea9b457ca4f0ed40384'
Cloning into 'src/mytardis'...
remote: Counting objects: 29527, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 29527 (delta 4), reused 3 (delta 0), pack-reused 29510
Receiving objects: 100% (29527/29527), 28.46 MiB | 2.47 MiB/s, done.
Resolving deltas: 100% (21870/21870), done.
Submodule path 'src/mytardis': checked out '0a75a1310e08f28dfa575a23c1da6d0f46e7672a'
$ cd mytardis
$ docker-compose up -d
ERROR: Couldn't find env file: /home/UNIWA/000XXXXX/tmp/test-mytardis-deploy/mytardis/env.POSTGRES

**Comment by dean-taylor** [comment]
Original instructions stated "edit Dockerfile and/or docker-compose.yml to your desired settings" but information on the addition of env_template.MODULE files is lacking. More detailed instructions in relation to this have been added. Please note that actual values for all required settings is not feasible as many of these are for security or specific environment. Reference to further reading if required have been placed in the template files.
